---
- name: Setup MySQL Master-Slave Replication
  hosts: mysql_master
  roles:
    - mysql

- name: Setup MySQL Slaves
  hosts: mysql_slaves
  roles:
    - mysql

- name: Install and Configure ProxySQL
  hosts: proxysql
  roles:
    - proxysql

- name: Setup Replication Manager
  hosts: mysql_nodes, proxysql
  become: yes
  roles:
    - replication_manager
    
- name: Install and configure ProxySQL Binlog Reader
  hosts: mysql_nodes
  become: true
  roles:
    - proxysql_mysql_binlog_reader
