- name: Install required dependencies
  apt:
    name:
      - gpg
      - wget
      - curl
      - lsb-release
      - gnupg
    state: present
    update_cache: yes

- name: Add Signal18 GPG Key (Ubuntu 20.04+)
  shell: |
    gpg --recv-keys --keyserver keyserver.ubuntu.com FAE20E50
    gpg --export FAE20E50 > /etc/apt/trusted.gpg.d/signal18.gpg

- name: Add Signal18 Replication Manager Repository
  shell: |
    echo "deb [signed-by=/etc/apt/trusted.gpg.d/signal18.gpg] http://repo.signal18.io/deb $(lsb_release -sc) 2.3" > /etc/apt/sources.list.d/signal18.list

- name: Update APT Repository Cache
  apt:
    update_cache: yes

- name: Install Replication Manager
  apt:
    name: replication-manager-osc
    state: present
